routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => '/'], function () {
	Route::get('/', ['as' => 'homePage', 'uses' => 'WebController@index']);

	Route::resource('/kebutuhan-diklat', 'RequirementController');
	Route::get('/get-kebutuhan-diklat', ['as' => 'getKebutuhan', 'uses' => 'RequirementController@get']);

	Route::resource('/agenda-diklat', 'ScheduleController');
	Route::get('/get-agenda-diklat', ['as' => 'getAgenda', 'uses' => 'ScheduleController@get']);
	Route::post('/post-agenda-diklat/{id}', ['as' => 'postAgenda', 'uses' => 'ScheduleController@update']);
	
	Route::get('/contact', ['as' => 'contact', 'uses' => 'WebController@contact']);

	Route::get('/details/{slug}', ['as' => 'detailsPage', 'uses' => 'WebController@contact'])->where('slug', '[\w\d\-\_]+');

	Route::resource('news', 'NewsController');
	Route::post('/post-news/{id}', ['as' => 'postNews', 'uses' => 'NewsController@update']);

	Route::resource('hasil-diklat', 'ResultsController');
	Route::get('/get-hasil-diklat', ['as' => 'getHasil', 'uses' => 'ResultsController@get']);
	Route::get('/paper-hasil-diklat/{id}', ['as' => 'getPaper', 'uses' => 'ResultsController@paper']);
	Route::post('/post-paper-diklat/{id}', ['as' => 'postPaper', 'uses' => 'ResultsController@update']);

	Route::resource('user-diklat', 'UserController');
	Route::get('/get-user-diklat', ['as' => 'getUser', 'uses' => 'UserController@get']);


	Route::group(['prefix' => 'dashboard', 'middleware' => ['user'], 'as' => 'dashboard.'], function () {
	// Route::group(['prefix' => 'dashboard', 'middleware' => ['user'], 'as' => 'dashboard.'], function () {
		Route::get('/', ['as' => 'dashboardPage', 'uses' => 'WebController@index']);
	});
});

Auth::routes();

resources/views/includes/alert.blade.php
        <div class="alert-group">
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Well done!</strong> You successfully read this important alert message.
            </div>
            <div class="alert alert-info">
                <strong>Heads up!</strong> This alert needs your attention, but it's not super important.
            </div>
            <div class="alert alert-warning alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Warning!</strong> Better check yourself, you're not looking too good.
            </div>
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Oh snap!</strong> Change a few things up and try submitting again.
            </div>
        </div>

resources/views/includes/footer.blade.php
<!-- footer -->
<section class="footer-top pt-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
             <!--    <form action="#" method="post">
                    <input type="email" placeholder="Enter your email..." name="email" required="">
                    <input type="submit" value="Subscribe">
                </form> -->
            </div>
            <div class="col-lg-6 social-icon mt-lg-0 mt-3 footer">
                <div class="icon-social">
                    <h3>Media Sosial Sidikmanis</h3>
                    <a href="{{ $setting->facebook }}" target="_blank" class="button-footr">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a href="{{ $setting->twitter }}" target="_blank" class="button-footr">
                        <i class="fab fa-twitter"></i>
                    </a>
                  
                </div>
            </div>
        </div>
    </div>
</section>
<section class="agile-footer middle w3ls-section">
    <div class="container">
        <div class="agileits_w3layouts-footer-bottom">
            <div class="row w3_agile-footer-grids py-5">
                <div class="col-lg-2 col-sm-3 mb-sm-0 mb-4 px-sm-0 px-4 w3_agile-footer1 f1">   
                    <h5 class="mb-3">Ringkas Menu </h5>
                        <ul class="w3ls-footer-bottom-list">
                        <li><a href="{{ route('homePage') }}">Beranda</a></li>
                        <li><a href="{{ route('kebutuhan-diklat.index') }}">Kebutuhan Diklat</a></li>
                        <li><a href="{{ route('agenda-diklat.index') }}">Agenda Diklat</a></li>
                        <li><a href="{{ route('hasil-diklat.index') }}">Hasil Diklat</a></li>
                        <li><a href="{{ route('news.index') }}">Berita</a></li>
                        <li><a href="{{ route('contact') }}">Kontak</a></li>
                    </ul>
                </div>
                <div class="col-lg-7 col-sm-9 mb-sm-0 mb-4 px-sm-0 px-4 row w3_agile-footer1 f2">
                    <div class="col-lg-3 col-sm-3  mb-sm-0 mb-4 inner-li">
                        <h5 class="mb-3">Account</h5>
                        <ul class="w3ls-footer-bottom-list">
                            <li><a href="#" data-toggle="modal" aria-pressed="false" data-target="#exampleModal">Login</a></li>
                            <li><a href="#" data-toggle="modal" aria-pressed="false" data-target="#exampleModal1">Create account</a></li>
                        </ul>
                    </div>
                    
                    <div class="col-lg-6 col-sm-7  mb-sm-0 mb-4 inner-li">
                        <h5 class="mb-3">Address</h5>
                        <ul class="w3ls-footer-bottom-list">
                            <li> <span class="fas fa-map-marker"></span> {{ $setting->address_line_one }}</li>
                            <li> <span class="fas fa-envelope"></span> <a href="{{ $setting->email }}"> {{ $setting->email }}</a> </li>
                            <li> <span class="fas fa-phone"></span> {{ $setting->phone }} </li>
                            <!-- <li> <span class="fas fa-globe"></span> <a href="#"> www.website.com</a> </li> -->
                            <!-- <li> <span class="fas fa-clock"></span> Working Hours : 8:00 a.m - 6:00 p.m</li> -->
                        </ul>
                    </div>
                    
                   <!--  <div class="col-lg-3 col-sm-2 inner-li">
                        <h5 class="mb-3">support</h5>
                        <ul class="w3ls-footer-bottom-list">
                            <li>
                                <a href="#">24/7 Service</a>
                            </li>
                            <li>
                                <a href="#">FAQ's</a>
                            </li>
                            <li>
                                <a href="#">Media Queries</a>
                            </li>
                            <li>
                                <a href="#">Others</a>
                            </li>
                        </ul>
                    </div> -->
                    <div class="clearfix"></div>
                </div>
                <div class="col-lg-3 col-md-12 px-sm-0 px-4 w3_agile-footer1 f3">
                        <h5 class="mb-3">Tweets Terakhir</h5>
                    <a class="twitter-timeline" href="{{ $setting->twitter }}" data-tweet-limit="2" data-theme="dark" data-link-color="#57C8EB" data-chrome="noheader nofooter noscrollbar noborders transparent">Tweets by BKPSDM Kab. Purwakarta</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

                </div>
            </div>
        </div>
    </div>
</section>
<section class="copyright py-4">
    <div class="agileits_w3layouts-copyright text-center">
        <p>{!! $setting->copyright !!}</p>
    </div>
</section>
<!-- //footer -->

resources/views/includes/head.blade.php
<title>@yield('title') - {{ $setting->website_title }}</title>
	
<!-- Meta tag Keywords -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<meta name="keywords" content="Corp Active Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript">
	addEventListener("load", function () {
		setTimeout(hideURLbar, 0);
	}, false);

	function hideURLbar() {
		window.scrollTo(0, 1);
	}
</script>
<!--// Meta tag Keywords -->

<link href="{{ asset('public/css/easy-responsive-tabs.css') }}" rel='stylesheet' type='text/css'/>

<!-- banner slider css file -->
<link href="{{ asset('public/css/JiSlider.css') }}" rel="stylesheet">
<!-- //banner slider css file -->

<!-- css files -->
<link rel="stylesheet" href="{{ asset('public/css/bootstrap.css') }}"> <!-- Bootstrap-Core-CSS -->
<link rel="stylesheet" href="{{ asset('public/css/style.css') }}" type="text/css" media="all" /> <!-- Style-CSS --> 
<link rel="stylesheet" href="{{ asset('public/css/fontawesome-all.css') }}"> <!-- Font-Awesome-Icons-CSS -->
<!-- //css files -->

<!-- web-fonts -->
<link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">

<!-- //web-fonts -->
	

resources/views/includes/header.blade.php
<!-- header -->
<header>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="{{ route('homePage') }}" title="{{ $setting->website_title }}">
                <!-- <i class="fas fa-boxes"></i> -->{{ $setting->website_title }}
            </a>
            <button class="navbar-toggler ml-md-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>




            <!-- Menu Bar -->
            @include('includes.menubar')
            <!-- Menu Bar -->

        </nav>
    </div>
</header>
<!-- //header -->

resources/views/includes/menubar.blade.php
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto text-center">
        <li class="nav-item mr-lg-3 {{ request()->is('/') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('homePage') }}" title="{{ $setting->website_title }}">Home
                <span class="sr-only">(current)</span>
            </a>
        </li>
        <li class="nav-item  mr-lg-3 {{ request()->is('kebutuhan-diklat') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('kebutuhan-diklat.index') }}">Kebutuhan Diklat</a>
        </li>
        <!-- <li class="nav-item  mr-lg-3 {{ request()->is('agenda-diklat') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('agenda-diklat.index') }}">Agenda Diklat</a>
        </li>
        <li class="nav-item  mr-lg-3 {{ request()->is('hasil-diklat') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('hasil-diklat.index') }}">Hasil Diklat</a>
        </li>
 -->
        <li class="nav-item dropdown mr-lg-3 {{ request()->is(['agenda-diklat','user-diklat','hasil-diklat']) ? 'active' : '' }}">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
                Diklat
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                @if(isAdmin())
                <a class="dropdown-item {{ request()->is('user-diklat') ? 'active' : '' }}" href="{{ route('user-diklat.index') }}">Peserta Diklat</a>
                <div class="dropdown-divider"></div>
                @endif
                <a class="dropdown-item {{ request()->is('agenda-diklat') ? 'active' : '' }}" href="{{ route('agenda-diklat.index') }}">Agenda Diklat</a>
                <a class="dropdown-item {{ request()->is('hasil-diklat') ? 'active' : '' }}" href="{{ route('hasil-diklat.index') }}">Hasil Diklat</a>
                <!-- <div class="dropdown-divider"></div> -->
                <!-- <a class="dropdown-item" href="about.html">Stats</a> -->
            </div>
        </li>
        <li class="nav-item mr-lg-3 {{ request()->is('news') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('news.index') }}">Berita</a>
        </li>
        <li class="nav-item {{ request()->is('contact') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('contact') }}">contact</a>
        </li>
    </ul>
    <div class="buttons">


        @if(Auth::check())
        <!-- <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><span style="color: #007bbd"> Logout</span></a></li> -->
        <a href="{{ route('logout') }}" type="button" class="btn btn-info btn-lg-block w3ls-btn px-4 text-uppercase mr-2" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            Logout
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>
        @else

        <button type="button" class="btn btn-info btn-lg-block w3ls-btn px-4 text-uppercase mr-2" data-toggle="modal"
            aria-pressed="false" data-target="#exampleModal">
            Login
        </button>
        <button type="button" class="btn btn-info btn-lg-block w3ls-btn1 px-4 text-uppercase" data-toggle="modal"
            aria-pressed="false" data-target="#exampleModal1">
            Register
        </button>
        @endif
    </div>
    
</div>

resources/views/includes/modal.blade.php
<!-- Login modal -->
<div class="modal fade bd-example-modal-lg" id="modalpopup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">

        @yield('modal')
		
	</div>
</div>
<!-- //Login modal -->

<!-- Login modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title text-uppercase" id="exampleModalLabel1">Login</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">

	            <form method="POST" action="{{ route('login') }}" class="p-3">
	                {{ csrf_field() }}

	                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
	                    <label for="email">Username / Email</label>
	                    <input type="email" class="form-control" name="email" value="{{ old('email') }}" autofocus>
	                    @if ($errors->has('email'))
	                    <span class="help-block">
	                        <strong>{{ $errors->first('email') }}</strong>
	                    </span>
	                    @endif
	                </div>

	                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
	                    <label for="password">Password</label>
	                    <input type="password" class="form-control" name="password">
	                    @if ($errors->has('password'))
	                    <span class="help-block">
	                        <strong>{{ $errors->first('password') }}</strong>
	                    </span>
	                    @endif
	                </div>

					<div class="right-w3l mt-4 mb-3">
						<!-- <input type="submit" class="submit-btn form-control" value="Login"> -->
	                    <button id="login-btn" type="submit" class="submit-btn form-control">Login</button> 

					</div>
	                    <!-- <a style="padding-left: 10px" href="{{ route('password.request') }}">Forget password?</a> -->
	            </form>

			</div>
		</div>
	</div>
</div>
<!-- //Login modal -->

<!-- Register modal -->
<div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title text-uppercase" id="exampleModalLabel1">Register Here</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form action="{{ route('register') }}" method="post" class="p-3">
	                {{ csrf_field() }}



					<div class="form-row">
		                <div class="form-group col-md-8{{ $errors->has('name') ? ' has-error' : '' }}">
		                    <label for="name">Name</label>
		                    <input type="text" name="name" class="form-control" value="{{ old('name') }}" placeholder="Name">
		                    @if ($errors->has('name'))
		                    <span class="help-block">
		                        <strong>{{ $errors->first('name') }}</strong>
		                    </span>
		                    @endif
		                </div>
		                <div class="form-group col-md-4{{ $errors->has('nip') ? ' has-error' : '' }}">
		                    <label for="name">NIP</label>
		                    <input type="number" name="nip" class="form-control" value="{{ old('nip') }}" placeholder="NIP">
		                    @if ($errors->has('nip'))
		                    <span class="help-block">
		                        <strong>{{ $errors->first('nip') }}</strong>
		                    </span>
		                    @endif
		                </div>

					</div>

					<div class="form-row">

						<div class="form-group col-md-4">
							<label for="recipient-name1">Golongan</label>
							<select class="form-control" placeholder="Golongan" name="gol" required="">
								<option value="I/a">I/a</option>
								<option value="I/b">I/b</option>
								<option value="I/c">I/c</option>
								<option value="I/d">I/d</option>
								<option value="II/a">II/a</option>
								<option value="II/b">II/b</option>
								<option value="II/c">II/c</option>
								<option value="II/d">II/d</option>
								<option value="III/a">III/a</option>
								<option value="III/b">III/b</option>
								<option value="III/c">III/c</option>
								<option value="III/d">III/d</option>
								<option value="IV/a">IV/a</option>
								<option value="IV/b">IV/b</option>
								<option value="IV/c">IV/c</option>
								<option value="IV/d">IV/d</option>
							</select>
						</div>

		                <div class="form-group col-md-8{{ $errors->has('position') ? ' has-error' : '' }}">
		                    <label for="name">Jabatan</label>
		                    <input type="text" name="position" class="form-control" value="{{ old('position') }}" placeholder="Jabatan">
		                    @if ($errors->has('position'))
		                    <span class="help-block">
		                        <strong>{{ $errors->first('position') }}</strong>
		                    </span>
		                    @endif
		                </div>
					</div>

	                <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }}">
	                    <label for="username">Username</label>
	                    <input type="text" name="username" class="form-control" value="{{ old('username') }}" placeholder="Username">
	                    @if ($errors->has('username'))
	                    <span class="help-block">
	                        <strong>{{ $errors->first('username') }}</strong>
	                    </span>
	                    @endif
	                </div>
	                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
	                    <label for="email">Email</label>
	                    <input type="email" name="email" class="form-control" value="{{ old('email') }}" placeholder="Email">
	                    @if ($errors->has('email'))
	                    <span class="help-block">
	                        <strong>{{ $errors->first('email') }}</strong>
	                    </span>
	                    @endif
	                </div>
	                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
	                    <label for="password">Password</label>
	                    <input type="password" class="form-control" name="password" placeholder="Password">
	                    @if ($errors->has('password'))
	                    <span class="help-block">
	                        <strong>{{ $errors->first('password') }}</strong>
	                    </span>
	                    @endif
	                </div>
	                <div class="form-group">
	                    <label for="password-confirm">Confirm Password</label>
	                    <input type="password" class="form-control" name="password_confirmation" placeholder="Konfirmasi Password">
	                </div>
					<div class="right-w3l mt-4 mb-3">
						<!-- <input type="submit" class="form-control" value="Create account"> -->
	                    <button id="register-btn" type="submit" class="submit-btn form-control">Submit</button> 
					</div>
				</form>

			</div>
		</div>
	</div>
</div>
<!-- //Register modal -->

resources/views/includes/scripts.blade.php
<!-- js-scripts -->		

	<!-- js -->
	<script type="text/javascript" src="{{ asset('public/js/jquery-2.1.4.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/js/bootstrap.js') }}"></script> <!-- Necessary-JavaScript-File-For-Bootstrap --> 
	<!-- //js -->	

	<!-- tabs -->
	<script src="{{ asset('public/js/easy-responsive-tabs.js') }}"></script>
	<script>
	$(document).ready(function () {
	$('#horizontalTab').easyResponsiveTabs({
	type: 'default', //Types: default, vertical, accordion           
	width: 'auto', //auto or any width like 600px
	fit: true,   // 100% fit in a container
	closed: 'accordion', // Start closed if in accordion view
	activate: function(event) { // Callback function if tab is switched
	var $tab = $(this);
	var $info = $('#tabInfo');
	var $name = $('span', $info);
	$name.text($tab.text());
	$info.show();
	}
	});
	$('#verticalTab').easyResponsiveTabs({
	type: 'vertical',
	width: 'auto',
	fit: true
	});
	});
	</script>
	<!--//tabs-->
	
	<!-- for-Testimonials -->
	<!-- required-js-files-->
	<link href="{{ asset('public/css/owl.carousel.css') }}" rel="stylesheet">
		<script src="{{ asset('public/js/owl.carousel.js') }}"></script>
			<script>
		$(document).ready(function() {
		  $("#owl-demo").owlCarousel({
			items : 1,
			lazyLoad : true,
			autoPlay : true,
			navigation : false,
			navigationText :  false,
			pagination : true,
		  });
		});
		</script>
	<!--//required-js-files-->
	<!-- //for-Testimonials -->

	<!-- start-smoth-scrolling -->
	<script src="{{ asset('public/js/SmoothScroll.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/js/move-top.js') }}"></script>
	<script type="text/javascript" src="{{ asset('public/js/easing.js') }}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){		
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
			});
		});
	</script>
	<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
			*/
								
			$().UItoTop({ easingType: 'easeOutQuart' });
								
			});
	</script>

	<!-- //here ends scrolling icon -->
	<!-- start-smoth-scrolling -->
	
	<script type="text/javascript" src="{{ asset('public/js/jquery.form.js') }}"></script>
	
	<script type="text/javascript" src="{{ asset('public/js/custom.js') }}"></script>
<!-- //js-scripts -->

resources/views/includes/sidebar.blade.php
<div class="col-md-4">
    <aside>
     <!--START NEWSLETTER-->
     <div class="widget newsletter">
        <form data-parsley-validate action="{{ route('searchRoute') }}" method="post">
            {{ csrf_field() }}
            <input type="text" name="search_keywords" class="newsletter-email" placeholder="ex: post title" required>
            <button class="newsletter-subscribe" type="submit"><i class="fa fa-search"></i> Search</button>
        </form>
        @if ($errors->has('search_keywords'))
        <p class="text-center text-danger" style="font-size: 12px; padding: 5px 0px;">{{ $errors->first('search_keywords') }}</p>
        @endif
    </div>
    <!--/END NEWSLETTER-->

  <!--START POPULAR CATEGORIES-->
  <div class="widget">
    <div class="widget-title">
        <h4>
            <i class="fa fa-rocket"></i>
            All Categories
        </h4>
    </div>
    <ul class="widget-popular-cat">
        @foreach($categories as $category)
        <li>
            <a href="{{ route('categoryPage', $category->id) }}" title="{{ $category->category_name }}"><i class="fa fa-angle-right"></i>{{ $category->category_name }}<span class="cat-count-1">{{ $category->post()->count() }}</span></a>
        </li>
        @endforeach
    </ul>
</div>
<!--/END POPULAR CATEGORIES-->

<!--START NEWSLETTER-->
<div class="widget newsletter">
    <div class="widget-title">
        <h4>
            <i class="ti-email"></i>
            NEWSLETTER
        </h4>
    </div>
    <div class="subscribe-image">
        <img src="{{ asset('public/web') }}/images/newsletter.png" alt="Newsletter">
        <p>Subscribe our newsletter to stay updated.</p>
    </div>
    <form data-parsley-validate id="subscribe_add_form" method="post">
        {{ csrf_field() }}
        <input type="text" name="email" class="newsletter-email" placeholder="ex: mail@mail.com" required>
        <button class="newsletter-subscribe" name="subscribe" type="button" id="store-button">Subscribe</button>
    </form>
    <p class="text-center text-danger" id="email-error"></p>
    <p class="text-center text-success" id="email-success"></p>
</div>
<!--/END NEWSLETTER-->

<!--START TAGS-->
<div class="widget">
    <div class="widget-title">
        <h4>
            <i class="ti-tag"></i>
            Tags
        </h4>
    </div>
    <ul class="tags-cloud">
        @foreach($tags as $tag)
        <li><a href="{{ route('tagPage', $tag->id) }}" title="{{ $tag->tag_name }}">{{ $tag->tag_name }} ({{ $tag->posts()->count() }})</a></li>
        @endforeach
    </ul>
</div>
<!--/END TAGS-->

<!--Facebook Page-->
@if(!empty($setting->facebook))
    <div class="widget">
        <div class="fb-page" data-href="{{ $setting->facebook }}" data-tabs="timeline" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
            <blockquote cite="{{ $setting->facebook }}" class="fb-xfbml-parse-ignore">
                <a href="{{ $setting->facebook }}">{{ $setting->website_title }}</a>
            </blockquote>
        </div>
        <div id="fb-root"></div>
        <script type="text/javascript">
            (function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12&appId=1227264524030761&autoLogAppEvents=1';
              fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));
      </script>
  </div>
  @endif
  <!--/Facebook Page-->

</aside>
</div>